#!/bin/bash
app=taiga
app_port=8010
domain=host.local
path=/$app

start_point=$(pwd)
install_path=/var/www/$app
source /usr/share/yunohost/helpers


sudo yunohost app checkurl $domain$path -a taiga \
    || (echo "Path not available: $domain$path" && exit 1)

sudo yunohost app checkurl $domain$path/api -a taiga \
    || (echo "Path not available: $domain$path/api" && exit 1)


sudo yunohost app checkurl $domain$path/admin -a taiga \
    || (echo "Path not available: $domain$path/admin" && exit 1)

sudo yunohost app checkurl $domain$path/events -a taiga \
    || (echo "Path not available: $domain$path/events" && exit 1)

sudo yunohost app checkurl $domain$path/media -a taiga \
    || (echo "Path not available: $domain$path/media" && exit 1)

sudo yunohost app checkurl $domain$path/static -a taiga \
    || (echo "Path not available: $domain$path/static" && exit 1)

sudo yunohost app checkport $app_port \
    || (echo "Port not available: $app_port" && exit 1)

sudo yunohost app checkport 8011 \
    || (echo "Port not available: 8011" && exit 1)

sudo yunohost app checkport 5555 \
    || (echo "Port not available: 5555" && exit 1)

sudo yunohost app checkport 5556 \
    || (echo "Port not available: 5556" && exit 1)

sudo apt-get install -y build-essential binutils-doc autoconf flex bison libjpeg-dev
sudo apt-get install -y libfreetype6-dev zlib1g-dev libzmq3-dev libgdbm-dev libncurses5-dev
sudo apt-get install -y automake libtool libffi-dev curl git tmux gettext

sudo apt-get install -y postgresql-9.4 postgresql-contrib-9.4
sudo apt-get install -y postgresql-doc-9.4 postgresql-server-dev-9.4


sudo apt-get install -y python3 python3-pip python-dev python3-dev python-pip virtualenvwrapper
sudo apt-get install libxml2-dev libxslt-dev
sudo apt-get install -y rabbitmq-server redis-server
sudo mkdir $install_path

sudo app=$app start_point=$start_point install_path=$install_path bash ./installers/api.bash

sudo app=$app start_point=$start_point install_path=$install_path bash ./installers/front.bash

sudo app=$app start_point=$start_point install_path=$install_path bash ./installers/events.bash

cd $start_point
sudo mkdir -p /var/log/taiga
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
sudo cp ../conf/circus.service /etc/systemd/system/circus.service
sudo systemctl daemon-reload
sudo yunohost service add circus
sudo yunohost service add rabbitmq-server
sudo yunohost service add redis-server
sudo yunohost service add postgresql
sudo service circus start
sudo service nginx reload
sudo yunohost app ssowatconf
